default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hoi_hrysd_org_development

test:
  <<: *default
  database: hoi_hrysd_org_test

production:
  <<: *default
  database: hoi_hrysd_org_production
